### PR TITLE
[WIP] IfcGridPlacement implementation

### LINKED ISSUE #64: Example file "grid-placement" is not working
The file is [here](../blob/development/testdata/IFC4x1ExampleFiles/official/E7_Placements_and_GIS_referencing/grid-placement.ifc).  Current version crashes.

### LINKED ISSUE #88: IfcGridPlacement not implemented
https://github.com/tumcms/Open-Infra-Platform/blob/50d59734feedd9f2601306aa5a33e2f6b56d68dc/Core/src/IfcGeometryConverter/PlacementConverter.h#L430-L436

### PR DESCRIPTION
**Pull request by SamuilsRulovs**
Added several functions: 

- convertIfcVirtualGridIntersection

WIP:

- convertIfcGridPlacement(draft)

Fixes #64 

*edit 20201025*: fixes #88 .

### CODE REVIEW

File: Core/src/IfcGeometryConverter/PlacementConverter.h [hunk 1]
```diff
@@ -757,6 +758,93 @@ namespace OpenInfraPlatform {
...
+						double Ydistance = intersection->OffsetDistances[1];
+						double Zdistance = intersection->OffsetDistances[2];
+						location[0] = location[0] + intersection->OffsetDistances[1];
+						location[1] = location[1] + intersection->OffsetDistances[0];
+						location[2] = location[2] + intersection->OffsetDistances[2];
+						break;
+					case 2:
+						double Xdistance = intersection->OffsetDistances[0];
+						double Ydistance = intersection->OffsetDistances[1];
+						ocation[0] = location[0] + intersection->OffsetDistances[1];
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/PlacementConverter.h]: Typo?

File: Core/src/IfcGeometryConverter/PlacementConverter.h [hunk 2]
```diff
@@ -757,6 +758,93 @@ namespace OpenInfraPlatform {
...
+					CurveConverterT<IfcEntityTypesT> grid_conv(GeomSettings(), UnitConvert(), this);
+
+					grid_conv.convertIfcCurve2D(intersection->IntersectingAxes[0], Xaxis, Xsegment_start_points);
+					grid_conv.convertIfcCurve2D(intersection->IntersectingAxes[1], Yaxis, Ysegment_start_points);
+					
+					std::vector<carve::geom::vector<2>> intersection_point;
+
+					for (int i = 0; i < Xaxis.size(); i++) {
+						X_Axis_Position = XAxis[i];
+						X_Axis_2Position = XAxis[i+1];
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/PlacementConverter.h]: This will overflow the border of the array. You are going till `< .size()`, with `[i+1]` you will go one beyond. Make sure to loop until `.size()-1`.

File: Core/src/IfcGeometryConverter/PlacementConverter.h [hunk 3]
```diff
@@ -757,6 +758,93 @@ namespace OpenInfraPlatform {
...
+						for (int j = 0; j <= Yaxis.size(); j++) {
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/PlacementConverter.h]: Same problem here. Also, why `<=`?

File: Core/src/IfcGeometryConverter/PlacementConverter.h [hunk 4]
```diff
@@ -757,6 +758,93 @@ namespace OpenInfraPlatform {
...
+							Y_Axis_Position = YAxis[i];
+							Y_Axis_2Position = YAxis[i+1];
+							if (GeomUtils::LineSegmentToLineIntersection(X_Axis_2Position, X_Axis_Position, Y_Axis_2Position, Y_Axis_Position, intersection_point)) {
+								goto stop;
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/PlacementConverter.h]: `goto` is bad programming. Yes, it is possible, but you need to exit both loops differently.

E.g.: set `j=Yaxis.size()` and `i=Xaxis.size()` - in this way, both loops will terminate.

File: Core/src/IfcGeometryConverter/PlacementConverter.h [hunk 5]
```diff
@@ -757,6 +758,93 @@ namespace OpenInfraPlatform {
...
+					
+					std::vector<carve::geom::vector<2>> intersection_point;
+
+					for (int i = 0; i < Xaxis.size(); i++) {
+						X_Axis_Position = XAxis[i];
+						X_Axis_2Position = XAxis[i+1];
+						for (int j = 0; j <= Yaxis.size(); j++) {
+							Y_Axis_Position = YAxis[i];
+							Y_Axis_2Position = YAxis[i+1];
+							if (GeomUtils::LineSegmentToLineIntersection(X_Axis_2Position, X_Axis_Position, Y_Axis_2Position, Y_Axis_Position, intersection_point)) {
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/PlacementConverter.h]: You should be using `LineSegmentToLineSegmentIntersection`.

File: Core/src/IfcGeometryConverter/PlacementConverter.h [hunk 6]
```diff
@@ -757,6 +758,93 @@ namespace OpenInfraPlatform {
...
+								goto stop;
+							}
+						}
+					}
+						
+					stop:
+					
+					carve::geom::vector<3> location = {0.0,0.0,0.0};
+					location[0] = intersection_point[0];
+					location[1] = intersection_point[1];
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/PlacementConverter.h]: intersection_point is 3D, right? If not, you need to get the vertical component somehow. Probably.

File: Core/src/IfcGeometryConverter/PlacementConverter.h [hunk 7]
```diff
@@ -757,6 +758,93 @@ namespace OpenInfraPlatform {
...
+						location[2] = location[2] + intersection->OffsetDistances[2];
+						break;
+					case 2:
+						double Xdistance = intersection->OffsetDistances[0];
+						double Ydistance = intersection->OffsetDistances[1];
+						ocation[0] = location[0] + intersection->OffsetDistances[1];
+						location[1] = location[1] + intersection->OffsetDistances[0];
+						break;
+					default:
+						throw oip::InconsistentGeometryException(intersection, "Number of coordinates is inconsistent.");
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/PlacementConverter.h]: its OffsetDistances that are inconsistent, right?

File: Core/src/IfcGeometryConverter/PlacementConverter.h [hunk 8]
```diff
@@ -757,6 +758,93 @@ namespace OpenInfraPlatform {
...
+
+					switch (grid_placement.which()) {
+					case 0:
+						return convertIfcDirection(grid_placement.get<0>());
+					case 1:
+						return convertIfcVirtualGridIntersection(grid_placement.get<1>());
+					default:
+						//location +  intersectiing axes[1]
+					}
+					return object_placement_matrix;
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/PlacementConverter.h:1004]: Where is `object_placement_matrix` defined?

You should calculate it, though. The returns are totally wrong.

**Review by pjanck — CHANGES_REQUESTED** [review]
Generally correct direction, but many mistakes :)

File: Core/src/IfcGeometryConverter/PlacementConverter.h (hunk 2 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/PlacementConverter.h]: Resolved: c4244fc

File: Core/src/IfcGeometryConverter/PlacementConverter.h (hunk 3 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/PlacementConverter.h]: Resolved: c4244fc

File: Core/src/IfcGeometryConverter/PlacementConverter.h (hunk 4 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/PlacementConverter.h]: Resolved: c4244fc

File: Core/src/IfcGeometryConverter/PlacementConverter.h (hunk 5 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/PlacementConverter.h]: Resolved: c4244fc

File: Core/src/IfcGeometryConverter/PlacementConverter.h (hunk 7 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/PlacementConverter.h]: Resolved: c4244fc

File: Core/src/IfcGeometryConverter/PlacementConverter.h (hunk 6 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/PlacementConverter.h]: I have added in 
c4244fc an equation (according to this: https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/schema/ifcgeometricconstraintresource/lexical/ifcvirtualgridintersection.htm), so I could get the vertical component. However, I am not sure, if I have correctly implemented it.

Comment (pjanck) [reply Core/src/IfcGeometryConverter/PlacementConverter.h]: Reading [here](https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/schema/ifcproductextension/lexical/ifcgrid.htm) - the grid axes are in 2D. I stand corrected.

**Review by pjanck — CHANGES_REQUESTED** [review]
As discussed over phone.

File: Core/src/IfcGeometryConverter/PlacementConverter.h (hunk 1 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/PlacementConverter.h]: Yes, thank you! I have resolved it here: 6b9a428

File: Core/src/IfcGeometryConverter/PlacementConverter.h (hunk 8 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/PlacementConverter.h:1004]: Resolved: 5d4ca19

File: Core/src/IfcGeometryConverter/GeomUtils.cpp [hunk 9]
```diff
@@ -634,23 +634,32 @@ bool GeomUtils::isPointOnLineSegment( double& target_lambda,
...
-								  carve::geom::vector<2>& v3, 
-								  carve::geom::vector<2>& v4, double & r, double & s)
+/*! \brief Calculates distances between start points of the segment and their intersection. 
+* \param[in] initialPointSeg1		Initial point of the first intersecting segment.			
+* \param[in] terminalPointSeg1		Terminal point of the first intersecting segment.
+* \param[in] initialPointSeg2		Initial point of the second intersecting segment.			
+* \param[in] terminalPointSeg2		Terminal point of the second intersecting segment.
+* \param[out] distToIntesection1	Distance from initialPointSeg1 to the segment intresection, which is calculated as section of the first segment. 
+* \param[out] distToIntesection2	Distance from initialPointSeg2 to the segment intresection, which is calculated as section of the second segment. 
+*/
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/GeomUtils.cpp:647]: missing `\return` explanation

File: Core/src/IfcGeometryConverter/GeomUtils.cpp [hunk 10]
```diff
@@ -634,23 +634,32 @@ bool GeomUtils::isPointOnLineSegment( double& target_lambda,
...
+bool LineToLineIntersectionHelper(const carve::geom::vector<2>& initialPointSeg1,
+								  const carve::geom::vector<2>& terminalPointSeg1,
+								  const carve::geom::vector<2>& initialPointSeg2,
+								  const carve::geom::vector<2>& terminalPointSeg2, 
+	double & distToIntesection1, double & distToIntesection2)
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/GeomUtils.cpp]: please make sure, that the indentation is consistent.

File: Core/src/IfcGeometryConverter/GeomUtils.cpp [hunk 11]
```diff
@@ -659,48 +668,76 @@ bool LineToLineIntersectionHelper(carve::geom::vector<2>& v1,
...
+* \param[in] terminalPointSeg1		Terminal point of the first intersecting segment.
+* \param[in] initialPointSeg2		Initial point of the second intersecting segment, which describes the direction of the line.
+* \param[in] terminalPointSeg2		Terminal point of the second intersecting segment, which describes the direction of the line.
+* \param[out] intersectionPoint		Coordinates of the intersection point between first line segment and second line.
+*/
+bool GeomUtils::LineSegmentToLineIntersection(const carve::geom::vector<2>& initialPointSeg1,
+												const carve::geom::vector<2>& terminalPointSeg1, 
+												const carve::geom::vector<2>& initialPointSeg2,
+												const carve::geom::vector<2>& terminalPointSeg2,
+	carve::geom::vector<2> & intersectionPoint)
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/GeomUtils.cpp]: - missing `\return` explanation
- please make sure, that the indentation is consistent

File: Core/src/IfcGeometryConverter/GeomUtils.cpp [hunk 12]
```diff
@@ -634,23 +634,32 @@ bool GeomUtils::isPointOnLineSegment( double& target_lambda,
...
-	const carve::geom::vector<2> vertex3to4 = v4 - v3;
-	if( vertex1to2.y / vertex1to2.x != vertex3to4.y / vertex3to4.x )
+	const carve::geom::vector<2> intersectingSegment1 = terminalPointSeg1 - initialPointSeg1;
+	const carve::geom::vector<2> intersectingSegment2 = terminalPointSeg2 - initialPointSeg2;
+	if (!(intersectingSegment1.x == 0. && intersectingSegment2.x == 0.) // if both x=0., then lines are parallel
+		&& (intersectingSegment1.x == 0. || intersectingSegment2.x == 0. || (intersectingSegment1.y / intersectingSegment1.x != intersectingSegment2.y / intersectingSegment2.x))) // common case
 	{
-		const double d = vertex1to2.x*vertex3to4.y - vertex1to2.y*vertex3to4.x;
+		const double d = intersectingSegment1.x*intersectingSegment2.y - intersectingSegment1.y*intersectingSegment2.x;
 		if( d != 0 )
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/GeomUtils.cpp]: always compare doubles with doubles -> `0.0`

File: Core/src/IfcGeometryConverter/GeomUtils.cpp [hunk 13]
```diff
@@ -659,48 +668,76 @@ bool LineToLineIntersectionHelper(carve::geom::vector<2>& v1,
...
+* \param[in] terminalPointSeg1		Terminal point of the first intersecting segment.
+* \param[in] initialPointSeg2		Initial point of the second intersecting segment.
+* \param[in] terminalPointSeg2		Terminal point of the second intersecting segment.
+* \param[out] intersectionPoint		Coordinates of the intersection point between first line segment and second line segment.
+*/
+bool GeomUtils::LineSegmentToLineSegmentIntersection(const carve::geom::vector<2>& initialPointSeg1,
+														const carve::geom::vector<2>& terminalPointSeg1,
+														const carve::geom::vector<2>& initialPointSeg2,
+														const carve::geom::vector<2>& terminalPointSeg2,
+	carve::geom::vector<2> & intersectionPoint)
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/GeomUtils.cpp]: - missing `\return` explanation
- please make sure, that the indentation is consistent

File: Core/src/IfcGeometryConverter/GeomUtils.cpp [hunk 14]
```diff
@@ -659,48 +668,76 @@ bool LineToLineIntersectionHelper(carve::geom::vector<2>& v1,
...
 		}
 	}
 	return false;
 }
 
+bool GeomUtils::LineToLineIntersection(const carve::geom::vector<2>& initialPointSeg1,
+										const carve::geom::vector<2>& terminalPointSeg1,
+										const carve::geom::vector<2>& initialPointSeg2,
+										const carve::geom::vector<2>& terminalPointSeg2,
+										carve::geom::vector<2> & intersectionPoint)
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/GeomUtils.cpp:742]: - doxygen comment missing
- please make sure, that the indentation is consistent

File: Core/src/IfcGeometryConverter/GeomUtils.cpp [hunk 15]
```diff
@@ -659,48 +668,76 @@ bool LineToLineIntersectionHelper(carve::geom::vector<2>& v1,
...
+														const carve::geom::vector<2>& terminalPointSeg2,
+	carve::geom::vector<2> & intersectionPoint)
 {
-	double r, s;
-	if( LineToLineIntersectionHelper(v1, v2, v3, v4, r, s) )
+	double distToIntesection1, distToIntesection2;
+	if( LineToLineIntersectionHelper(initialPointSeg1, terminalPointSeg1, initialPointSeg2, terminalPointSeg2, distToIntesection1, distToIntesection2) )
 	{
-		if (r >= 0 && r <= 1)
+		if (distToIntesection1 >= 0 && distToIntesection1 <= 1)
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/GeomUtils.cpp]: again, comparing doubles with integers is bad practice. Use `0.0` and `1.0`.

File: Core/src/IfcGeometryConverter/PlacementConverter.h [hunk 16]
```diff
@@ -754,97 +754,152 @@ namespace OpenInfraPlatform {
...
+						intersecting3DAxes1 = carve::geom::VECTOR(intersectingAxes1.x, intersectingAxes1.y, 0.0 );
+						orthogonalComplement = carve::geom::VECTOR(-intersectingAxes1.y, intersectingAxes1.x, 0.0);
+						
+						//cross product of IntersectingAxes[1] and the orthogonal complement of the IntersectingAxes[1] 
+						crossProduct = carve::geom::cross(intersecting3DAxes1, orthogonalComplement);
+						location = location + crossProduct;
+						
+						location.x = location.x + newIntersectionPoint.x;
+						location.y = location.y + newIntersectionPoint.y;
+						location.z = location.z + intersection->OffsetDistances[2];
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/PlacementConverter.h]: This is wrong. I see that we need to make a small excursion to vector algebra.

**Review by pjanck — CHANGES_REQUESTED** [review]
The calculations are definitely not correct (yet). We need a session, where we go through the topic.

File: Core/src/IfcGeometryConverter/PlacementConverter.h [hunk 17]
```diff
@@ -758,28 +758,40 @@ namespace OpenInfraPlatform {
...
+
+					std::vector<carve::geom::vector<2>> axis;
+					std::vector<carve::geom::vector<2>> segmentStartPoints;
+					bool sameSense;
+					if (gridAxis->SameSense) {
+						sameSense = true;
+					}
+					else {
+					sameSense = false;
+					}
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/PlacementConverter.h]: I had something else in mind.

You don't need to return the `sameSense` parameter, as you can apply it within this function already. After the `gridConv.convert...`, you could do the following:

```
if( ! gridAxis->SameSense )
    // turn around the axis
    std::reverse( std::begin(axis), std::end(axis) );
```

In this way, the axis "runs" in the other direction, applying the `SameSense` attribute, so that the calculation of offsets in the calling function happen correctly (at least I think so).

**Review by pjanck — CHANGES_REQUESTED** [review]
Good work so far!

File: Core/src/IfcGeometryConverter/GeomUtils.cpp (hunk 15 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/GeomUtils.cpp]: Resolved: 8f80eb1

File: Core/src/IfcGeometryConverter/GeomUtils.cpp (hunk 12 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/GeomUtils.cpp]: Resolved: 8f80eb1

File: Core/src/IfcGeometryConverter/PlacementConverter.h (hunk 17 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/PlacementConverter.h]: Resolved: a619817

File: Core/src/IfcGeometryConverter/GeomUtils.cpp (hunk 14 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/GeomUtils.cpp:742]: Resolved: a619817 and 8f80eb1

File: Core/src/IfcGeometryConverter/GeomUtils.cpp (hunk 13 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/GeomUtils.cpp]: Resolved: a619817 and 8f80eb1

File: Core/src/IfcGeometryConverter/GeomUtils.cpp (hunk 11 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/GeomUtils.cpp]: Resolved:  a619817 and 8f80eb1

File: Core/src/IfcGeometryConverter/GeomUtils.cpp (hunk 10 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/GeomUtils.cpp]: Resolved: 8f80eb1

File: Core/src/IfcGeometryConverter/GeomUtils.cpp (hunk 9 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/GeomUtils.cpp:647]: Resolved: a619817

File: Core/src/IfcGeometryConverter/PlacementConverter.h (hunk 16 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/PlacementConverter.h]: Resolved: 4dc4fbf

File: Core/src/IfcGeometryConverter/GeomUtils.cpp [hunk 18]
```diff
@@ -641,6 +641,7 @@ bool GeomUtils::isPointOnLineSegment( double& target_lambda,
 * \param[in] terminalPointSeg2		Terminal point of the second intersecting segment.
 * \param[out] distToIntesection1	Distance from initialPointSeg1 to the segment intresection, which is calculated as section of the first segment. 
 * \param[out] distToIntesection2	Distance from initialPointSeg2 to the segment intresection, which is calculated as section of the second segment. 
+* \return							Returns a boolean statement, if lines are intersecting with each other.
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/GeomUtils.cpp]:
```suggestion
* \return							Returns true, if lines are intersecting with each other. False otherwise.

```

**Review by pjanck — CHANGES_REQUESTED** [review]
And the changes as discussed over the TelCo.

**Comment by pjanck** [comment]
Sadly, this development needs Inverse attributes of `IfcGridAxis` in order to reach the `ObjectPlacement` of `IfcGrid`. So waiting for #197 to be completed and merged.

**Review by pjanck — COMMENTED** [review]
Waiting for #197 to correctly apply position of `IfcGrid`.

File: Core/src/IfcGeometryConverter/PlacementConverter.h [hunk 19]
```diff
@@ -758,7 +758,26 @@ namespace OpenInfraPlatform {
 					return object_placement_matrix;
                 }
 				
-				std::vector<carve::geom::vector<2>> convertIfcGridAxis(const EXPRESSReference<typename IfcEntityTypesT::IfcGridAxis>& gridAxis) const throw(...) {
+				/**********************************************************************************************/
+				/*! \brief Convert \c IfcGridAxis
+				* \param[in] IfcGridAxis			The \c IfcGridAxis to be converted
+				* \return							Axis curve of the grid
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/PlacementConverter.h]:
```suggestion
				* \return							the tessellated axis' curve (an ordered array of points, i.e. a polyline)
```

File: Core/src/IfcGeometryConverter/PlacementConverter.h [hunk 20]
```diff
@@ -776,10 +795,23 @@ namespace OpenInfraPlatform {
 					return axis;
 				}
 
+				/**********************************************************************************************/
+				/*! \brief Convert \c IfcVirtualGridIntersection to a transformation matrix
+				* \param[in] intersection			The \c IfcVirtualGridIntersection to be converted
+				* \return location					Location of the grid.
+				* \return intersectingAxes1			Tangent of the first intersecting axis
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/PlacementConverter.h]:
```suggestion
				* \return 					A tuple: 1: Location of the grid, 2: tangent of the first intersecting axis	
```

a `\return` cannot be named (or can it?), so the return needs to be described in one line

**Review by pjanck — CHANGES_REQUESTED** [review]
Great idea to review the comments of the grid conversion code! Small suggestions for improvement.

File: Core/src/IfcGeometryConverter/PlacementConverter.h (hunk 20 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/PlacementConverter.h]: Resolved: 3390ed1

File: Core/src/IfcGeometryConverter/PlacementConverter.h (hunk 19 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/PlacementConverter.h]: Resolved: 3390ed1

File: Core/src/IfcGeometryConverter/GeomUtils.cpp (hunk 18 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/GeomUtils.cpp]: Resolved: ea57d5d

**Review by pjanck — COMMENTED** [review]
Still waiting for the inverse to be merged. Otherwise looks finished.

**Comment by pjanck** [comment]
Please add [these examples]/https://forums.buildingsmart.org/t/what-about-grids/2703/10) as well.

**Review by pjanck — CHANGES_REQUESTED** [review]
Please add [these examples](https://forums.buildingsmart.org/t/what-about-grids/2703/10) as well.

**Comment by pjanck** [comment]
Following #322 this PR can now be completed.

File: Core/src/IfcGeometryConverter/PlacementConverter.h [hunk 21]
```diff
@@ -779,20 +781,71 @@ namespace OpenInfraPlatform {
...
-					return axis;
+				carve::math::Matrix getGridPosition(const EXPRESSReference< typename IfcEntityTypesT::IfcGrid> grid, 
+					std::vector<EXPRESSReference<typename IfcEntityTypesT::IfcObjectPlacement>>& alreadyApplied
+				)const throw(...)
+				{
+					if (grid->ObjectPlacement) {
+						return convertIfcObjectPlacement(grid->ObjectPlacement, alreadyApplied);
+					}
+					else {
+						throw oip::InconsistentModellingException(grid, "Impossible to define a position of the grid");
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/PlacementConverter.h]: The correct error would be "An IfcPositioningElement must have a placement".

Siehe WHERE rule bei der Definition von `IfcPositioningElement`.

File: Core/src/IfcGeometryConverter/PlacementConverter.h [hunk 22]
```diff
@@ -779,20 +781,71 @@ namespace OpenInfraPlatform {
...
 					if (!gridAxis->SameSense)
 						// turn around the axis
-						std::reverse(std::begin(axis), std::end(axis));
+						std::reverse(std::begin(axisVector), std::end(axisVector));
+
+					if (!gridAxis->PartOfU.empty() && gridAxis->PartOfV.empty() && gridAxis->PartOfW.empty()) {
+						for (const auto& grid : gridAxis->PartOfU)
+						{
+							gridPositionMatrix = getGridPosition(grid, alreadyApplied);
+						}
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/PlacementConverter.h]:
```suggestion
						gridPositionMatrix = getGridPosition(gridAxis->PartOfU[0], alreadyApplied);
```

File: Core/src/IfcGeometryConverter/PlacementConverter.h [hunk 23]
```diff
@@ -779,20 +781,71 @@ namespace OpenInfraPlatform {
 					//			WR2: (SIZEOF(PartOfU) = 1) XOR(SIZEOF(PartOfV) = 1) XOR(SIZEOF(PartOfW) = 1);
 					//	END_ENTITY;
 
-					std::vector<carve::geom::vector<2>> axis;
+					std::vector<carve::geom::vector<2>> axisVector;
+					carve::math::Matrix gridPositionMatrix;
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/PlacementConverter.h]: Set this to the default of `IDENT()` - identity matrix.

File: Core/src/IfcGeometryConverter/PlacementConverter.h [hunk 24]
```diff
@@ -779,20 +781,71 @@ namespace OpenInfraPlatform {
...
+					if (grid->ObjectPlacement) {
+						return convertIfcObjectPlacement(grid->ObjectPlacement, alreadyApplied);
+					}
+					else {
+						throw oip::InconsistentModellingException(grid, "Impossible to define a position of the grid");
+					}
+				}
+				
+				std::vector<carve::geom::vector<2>> applyGridPositionToAxis(const carve::math::Matrix gridPositionMatrix,
+					const std::vector<carve::geom::vector<2>> axisVector
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/PlacementConverter.h]: by reference! ( `&` )

File: Core/src/IfcGeometryConverter/PlacementConverter.h [hunk 25]
```diff
@@ -779,20 +781,71 @@ namespace OpenInfraPlatform {
...
+				)const throw(...) 
+				{
+					std::vector<carve::geom::vector<2>> axisVectorOnGrid;
+					
+					for (int i = 0; i < axisVector.size(); i++) {
+						carve::geom::vector<2> axis = axisVector.at(i);
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/PlacementConverter.h]: Simpler syntax would be:

```suggestion
					for (const auto axis : axisVector) {
```

Also rename `axis` to `pnt` - it is a point :D

File: Core/src/IfcGeometryConverter/PlacementConverter.h [hunk 26]
```diff
@@ -779,20 +781,71 @@ namespace OpenInfraPlatform {
...
+					}
+					else if (gridAxis->PartOfU.empty() && gridAxis->PartOfV.empty() && !gridAxis->PartOfW.empty()) {
+						for (const auto& grid : gridAxis->PartOfW)
+						{
+							gridPositionMatrix = getGridPosition(grid, alreadyApplied);
+						}
+						return applyGridPositionToAxis(gridPositionMatrix, axisVector);
+					}
+					else  {
+						oip::InconsistentModellingException(gridAxis, "IfcGridAxis can only refer to a single instance of IfcGrid.");
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/PlacementConverter.h]: throw!

**Review by pjanck — CHANGES_REQUESTED** [review]
Some minor improvements.

File: Core/src/IfcGeometryConverter/PlacementConverter.h (hunk 21 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/PlacementConverter.h]: Resolved: f1d242b

File: Core/src/IfcGeometryConverter/PlacementConverter.h (hunk 22 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/PlacementConverter.h]: Resolved: f1d242b

File: Core/src/IfcGeometryConverter/PlacementConverter.h (hunk 24 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/PlacementConverter.h]: Resolved: f1d242b

File: Core/src/IfcGeometryConverter/PlacementConverter.h (hunk 23 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/PlacementConverter.h]: Resolved: f1d242b

File: Core/src/IfcGeometryConverter/PlacementConverter.h (hunk 25 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/PlacementConverter.h]: Resolved: f1d242b

File: Core/src/IfcGeometryConverter/PlacementConverter.h (hunk 26 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/PlacementConverter.h]: Resolved: f1d242b

**Review by pjanck — APPROVED** [review]
Great work!
