### PR TITLE
Ignoring commented lines for OFF Files

### LINKED ISSUE #382: [BUG] Ignore comments within Off files
**Describe the bug**
Off files can include comment lines starting with "#".
These lines should be ignored in the whole file.
At the moment comment lines are only ignored at the very beginning of the file.

**To Reproduce**
1. Take a off file with comments somewhere in the middle of the file
2. Try to open it

### PR DESCRIPTION
**Pull request by Elvira2227**
Added new function `getNextUncommentedLine` to read only uncommented lines for OFF files

Fixes #382

### CODE REVIEW

File: Core/src/OffConverter/OffReader.cpp [hunk 1]
```diff
@@ -52,7 +52,11 @@ std::shared_ptr<OffModel> OffReader::readFile(const std::string& filename)
 		while (std::getline(offFile, line) && line != "OFF");
 
 		//read number of elements
-		getline(offFile, line);
+		//getline(offFile, line);
+		if (!OffReader::getNextUncommentedLine(offFile, line))
+		{
+			return false;
+		}
```
Comment (jschlenger) [inline Core/src/OffConverter/OffReader.cpp]: If I'm not mistaken return false will exit the whole OffReader::readfile function.
I'm quite sure that's not what you try to do. Maybe you need a while loop here?

File: Core/src/OffConverter/OffReader.cpp [hunk 2]
```diff
@@ -81,7 +85,11 @@ std::shared_ptr<OffModel> OffReader::readFile(const std::string& filename)
 		for (int i = 0; i < nrOfFaces; i++)
 		{
 			//which type of face (triangle, quad, ...)
-			std::getline(offFile, line);
+			if (!OffReader::getNextUncommentedLine(offFile, line))
+			{
+				return false;
+			}
```
Comment (jschlenger) [inline Core/src/OffConverter/OffReader.cpp]: Same as above

File: Core/src/OffConverter/OffReader.cpp [hunk 3]
```diff
@@ -130,7 +138,11 @@ std::vector<buw::Vector3f> OffReader::readVertices(const int nrOfVertices,
 	std::vector<buw::Vector3f> allVertices;
 	for (int i = 0; i < nrOfVertices; i++)
 	{
-		std::getline(offFile, line);
+		//std::getline(offFile, line);
+		if (OffReader::getNextUncommentedLine(offFile, line))
+		{
+			line;
+		}
```
Comment (jschlenger) [inline Core/src/OffConverter/OffReader.cpp]: line; doesn't do anything

File: Core/src/OffConverter/OffReader.cpp [hunk 4]
```diff
@@ -241,5 +253,20 @@ buw::Vector3f OffReader::calcNormal(const buw::Vector3f& vertex1,
...
+bool OffReader::getNextUncommentedLine(std::ifstream& offFile, std::string& line)
+{
+	while (std::getline(offFile, line))
+	{
+		for (int i = 0; i < line.size(); i++)
+		{
+			if (line[i] != '#')
+			{
+				return true;
+			}
```
Comment (jschlenger) [inline Core/src/OffConverter/OffReader.cpp]: The first time a character is != # this function will stop completely and return true.
You also have to be sure to handle lines like "1.0  0.0 1.4142 #comment" right.
Even though this contains a comment we need all the information up until the # sign

**Review by jschlenger — COMMENTED** [review]
I suggest you use the example from here https://en.wikipedia.org/wiki/OFF_(file_format) , delete the color values for now but still leave the comments #red, #green, ...
Store it in a file and try to open it. Step through the code with the debugger to check where your code doesn't behave as expected.

File: Core/src/OffConverter/OffReader.cpp (hunk 4 above)
Comment (Elvira2227) [reply Core/src/OffConverter/OffReader.cpp]: Yes, you are right. In the last commit, I decided to read the code this way (but not quite right), but then I saw that our code in any case reads only a certain number of first characters (for example, for the first 4 characters from the line) and therefore will not a priori read comments at the end of the line.
Another story is when a comment is left accidentally or deliberately inside the points like "1 #comment 1 0". Perhaps we should eliminate this option too?

File: Core/src/OffConverter/OffReader.cpp (hunk 1 above)
Comment (Elvira2227) [reply Core/src/OffConverter/OffReader.cpp]: To check it, I took our file from the testdata and added randomly comments. I checked the code with debugs and it really doesn't count comments. 
This new function already iterates in its body and returns only the line that is free of comments. 
For example:
image

File: Core/src/OffConverter/OffReader.cpp (hunk 4 above)
Comment (jschlenger) [reply Core/src/OffConverter/OffReader.cpp]: The way theses comments are usually handled is that starting from the # sign the rest of the line is treated as a comment because otherwise it would be necessary to have a second sign to be able to tell where the comment ends 
I guess that off does not allow having comments in the middle of the line as you described it

**Comment by jschlenger** [comment]
Regarding the color question in the live meeting. I just took a look at the OffReader code. Using the same color value for all of the vertices should definitely be fine since the Off format defines one color per face.

**Comment by jschlenger** [comment]
Once you got everything working you could add a unit test for a off file with comments and colors. You can also test the off. files mentioned in issue #467

**Review by jschlenger — COMMENTED** [review]
Good work!
