### PR TITLE
Correcting PlacementConverterImpl.cpp

### LINKED ISSUE #328: [BUG] Compilation with 4x1 is broken
**Describe the bug**
Compilation is broken with IFC4x1.

Probably because of:

https://github.com/tumcms/Open-Infra-Platform/blob/397303840ab874779c2f3c6e2709361c83ab42e3/Core/src/IfcGeometryConverter/PlacementConverterImpl.cpp#L18-L21

It should be like:

https://github.com/tumcms/Open-Infra-Platform/blob/397303840ab874779c2f3c6e2709361c83ab42e3/Core/src/DataManagement/General/Data.cpp#L34-L38

**To Reproduce**
1. Compile with IFC4x1
1. See error

**CMake configuration**
If applicable, list any special configurations you have selected in CMake.
- EARLYBINDING_WITH_IFC4x1: selected

**Additional context**

### PR DESCRIPTION
**Pull request by SamuilsRulovs**
Fixes #328 .

### CODE REVIEW

File: Core/src/IfcGeometryConverter/PlacementConverterImpl.cpp [hunk 1]
```diff
@@ -15,9 +15,28 @@
...
+#include "EarlyBinding\IFC4X1\src\reader/IFC4X1Reader.h"
+#include "EarlyBinding\IFC4X1\src\EMTIFC4X1EntityTypes.h"
+#include "EarlyBinding\IFC4X1\src\IFC4X1.h"
+#endif
+
+#ifdef OIP_MODULE_EARLYBINDING_IFC4X3_RC1
+#include "EarlyBinding\IFC4X3_RC1\src\reader/IFC4X3_RC1Reader.h"
+#include "EarlyBinding\IFC4X3_RC1\src\EMTIFC4X3_RC1EntityTypes.h"
+#include "EarlyBinding\IFC4X3_RC1\src\IFC4X3_RC1.h"
 #endif
```
Comment (pjanck) [inline Core/src/IfcGeometryConverter/PlacementConverterImpl.cpp]: Only the 4x1 includes are needed. Remove the rest.

**Review by pjanck — CHANGES_REQUESTED** [review]

File: Core/src/IfcGeometryConverter/PlacementConverterImpl.cpp (hunk 1 above)
Comment (SamuilsRulovs) [reply Core/src/IfcGeometryConverter/PlacementConverterImpl.cpp]: Resolved: 7256a41

**Review by pjanck — APPROVED** [review]
